### ISSUE TITLE
Add ability to initialize nested structure for params_for

### ISSUE THREAD

**Issue by yordis** [beam-community/ex_machina#279]
Right now I have `Note` and `Card`

```
def card_factory do
    %Card{
      favorited: false,
      pinned: false,
      created_by: build(:account)
    }
  end

  def note_factory do
    %Note{
      title: Faker.String.base64(),
      description: Faker.Lorem.paragraph(5),
      card: build(:card),
      account: build(:account)
    }
  end
```

I want to be able to initial the parameters for note including the card attrs as well.

#### Example

```elixir
params_for(:note, %{
  card: params_for(:card)
})
```

For some reason `card` is getting remove from my attrs

**Comment by germsvel** [comment]
Hi @yordis, 

I believe `params_for` intentionally removes any associations. From the [params_for docs](https://hexdocs.pm/ex_machina/ExMachina.Ecto.html#c:params_for/2)

> Will return a map with the fields and virtual fields, but without the Ecto metadata, the primary key, or any belongs_to associations. This will recursively act on has_one associations and Ecto structs found in has_many associations.

Do you know if [params_with_assocs/2](https://hexdocs.pm/ex_machina/ExMachina.Ecto.html#c:params_with_assocs/2) might fit your use case?
