### ISSUE TITLE
Building a params_with_assoc provides only FK's but not associated record.

### ISSUE THREAD

**Issue by michaelfich** [beam-community/ex_machina#368]
If your changeset uses `put_assoc`, testing it with a `params_with_assoc` makes the function kinda blows up at the moment as the FK's are present in `params_with_assoc` as opposed to the associated record itself.

I'm curious if it's been considered to use an associated record instead, or perhaps another function altogether that associates the record itself?

**Comment by germsvel** [comment]
I know this has been open for some time, but I also just ran into this issue, so I wanted to add another comment. 

I think it would make sense to either add a different function that provides the associated record, or repurpose `params_with_assocs` to include the records and move the logic for what is now `params_with_assocs` to something like `params_with_assoc_ids` (not sure what a good name would be). 

I think the intention behind `params_for` and `params_with_assocs` was to have functions that gave something like parameters used Phoenix controllers. But I tend to think of them more broadly (and I'm guessing others do too) as the map version of my factory. So it's a bit confusing to see `params_for` and `params_with-assocs` behave so differently from what `build` gives us.

**Comment by marcandre** [comment]
Just wanted to chime in about both how confusing the current situation is and how unsatisfactory it is because there is no builtin way to get the params for the assoc.

Typically, a form will have `inputs_for :my_belongs_to`, and the changeset does not cast `:my_belongs_to_id` and instead does `cast_assoc(:my_belongs_to)`.

I don't personally understand why `params_for` does not return the params for the `belongs_to` assocs.

**Comment by marcandre** [comment]
Unless I'm missing something, this is compounded by the fact that neither `params_for` nor `params_with_assocs` will do the right thing for an `has_many` that itself `belongs_to`:

```
def customer_factory() do
  %Customer{
    orders: build_list(1, :order)
  }
end

def order_factory() do
  %Order{
    product: build(:product)
  }
end

def product_factory do
  %Product{
    color: :green
  }
end

# No way to get the desired results with _any_ data for `product` from a customer:

%{orders: [product: _]} = params_for(:customer) # => not a match
%{orders: [product: _]} = params_with_assoc(:customer) # => not a match
%{orders: [product_id: _]} = params_with_assoc(:customer) # => not a match
```
