### ISSUE TITLE
There is no option to pass opts

### ISSUE THREAD

**Issue by mojidabckuu** [beam-community/ex_machina#382]
Never used ex_machina without Ecto under the hood. Today faced with a case when I want to pass *Shared options* to my Repo's insert function. Barely reviewing the code I found that the "core"  in `insert!`call doesn't use `opts` parameter
```elixir
record
|> cast
|> repo.insert!
```
and seems there is no way to pass it

So I am looking for something like this

```elixir
defmodule MyApp.Factory do
  use ExMachina.Ecto, repo: MyApp.Repo, opts: [foobar: :enable]
  ...
end
```
where later this opts will be passed as a part of the insert

**Comment by germsvel** [comment]
Hi @mojidabckuu I think what you're looking for has an open PR, and we're looking for someone to add tests to it, if you're up for it! https://github.com/thoughtbot/ex_machina/pull/377

**Comment by germsvel** [comment]
I just pushed v2.6.0 of ExMachina which includes passing Repo options to [`insert/3`](https://hexdocs.pm/ex_machina/2.6.0/ExMachina.Ecto.html#c:insert/3). Hope that helps with this issue!
