### ISSUE TITLE
Allow sequences indices to be persisted between runs

### ISSUE THREAD

**Issue by LandonSchropp** [beam-community/ex_machina#418]
I've found the `Factory` methods provided by Ex Machina to be very useful in development. Often, when I'm manually testing code in `IEx` it's handy to be able to quickly insert a record into the database.

One issue I've run into with this is that sequence IDs are not persisted between sessions. If my record uses a sequence and has a uniqueness constraint, I'll get errors until I've called it enough times to cause the constraint to go away.

If possible, it would be great if there were a way to configure Ex Machina to persist sequence IDs between calls. For example, if I fired up `iex -S mix` and ran the following:

``` elixir
Factory.insert(:user) # %User{ username: "user1" } 
Factory.insert(:user) # %User{ username: "user2" }
```

And then I closed IEx and restarted it, it would be awesome if it had this behavior:

``` elixir
Factory.insert(:user) # %User{ username: "user3" } 
Factory.insert(:user) # %User{ username: "user4" }
```

**Comment by germsvel** [comment]
Thanks for opening the issue @LandonSchropp! Currently, sequences use Agents to hold the state for the sequence. Your suggestion means we'd have to switch to saving the state in some other way. I'm not sure how we would be accomplish that. But if you have ideas, I'd be happy to review a pull-request. 

In the meantime, I know it's probably not ideal, but you could modify the factory when you do manual testing to pass the `start_at` option to the sequence. You can see that in [the sequence docs](https://hexdocs.pm/ex_machina/ExMachina.html#sequence/3): 

```elixir
def user_factory do
  %{
    # Will generate "me-100@foo.com" then "me-101@foo.com", etc.
    email: sequence(:email, &"me-#{&1}@foo.com", start_at: 100),
  }
end
```

Do you think that would help?

**Comment by LandonSchropp** [comment]
Thanks for the reply @germsvel! Your suggestion is definitely helpful in quickly solving my problem. 🙂

What I've done in the past with `Fabricator` in Ruby was to patch the sequence generator and store the index to a temp file on every index generation. When the Fabricator first loaded, I would read the last sequence index from the disk and start it there.

I totally understand if this isn't something you're interested in adding to your package. I realize this isn't standard usage for factories—although it's useful!—so I'm content in closing this if you feel like it's out of scope.

If it's functionality you're interested in, I'm happy to create a draft PR around it.

Thanks!

**Comment by doomspork** [comment]
@itamm15 since a Agent is just a specialized GenServer for storing and retrieving data, could you help me understand what advantage you see switching this?

**Comment by itamm15** [comment]
Hello @doomspork, thanks for your quick response! 
All I meant was to have one, global state to persist the indices between runs :)
