### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by aj-foster** [beam-community/ex_machina#423]
Hello there 👋🏼 

It looks like this project may no longer be maintained. Does @thoughtbot plan to continue supporting this effort, or can we work to transition it to a community-led initiative?

Thanks for your time!

**Comment by fabriziosestito** [comment]
I am also interested in knowing this, just browsing the issues to search for recent activity and found this issue.
We are probably on the same boat as @aj-foster, plenty of our projects depend on `ex_machina` for testing.

**Comment by brimatteng** [comment]
Hey thanks for asking! At thoughtbot we usually have more active maintainership when we work on client projects that use our libraries. We don't currently have too many active elixir devs or projects. There won't be new features but there also shouldn't be breaking changes for a while. Feel free to open PRs for bugs or language compatibility changes while we figure out our approach for projects that don't get enough attention. You can tag me for reviews if you need

**Comment by aj-foster** [comment]
Thanks for your response. `ex_machina` is a valuable project for the community, so whatever you decide, we're here to help!

**Comment by yordis** [comment]
Hey @brimatteng, as @aj-foster pointed out, `ex_machina` is crucial to the Elixir ecosystem. I would like to offer my support with any tasks to alleviate the burden on you and help the ecosystem.

At the very minimum, I am doing my best to help Ueberauth and Tesla make minor improvements and guide people as much as possible.

So let me know if you need help here as well.

Cheers,

**Comment by epinault** [comment]
Same here. We depend on it and would be happy to provide at least some package update

**Comment by epinault** [comment]
@brimatteng how does your company feel about adding more OSS contributors? Also  I work for Podium who is heavily using Elixir and we would be happy to contribute and give back to the Elixir community

**Comment by yordis** [comment]
@doomspork could we propose taking the project under https://github.com/beam-community? 🙏🏻

**Comment by doomspork** [comment]
@yordis that would be awesome if folks are open to it! I'm in full support 🎉

**Comment by brimatteng** [comment]
Thanks for following up! I've been talking with devs and former devs from thoughtbot about how we could open this up better for community support. I'm not opposed to shifting this project and possibly thoughtbot/bamboo to a community ownership, still working on what that would look like and what steps thoughtbot needs to take for that

**Comment by brimatteng** [comment]
Hi all, current plan is to migrate ownership from thoughtbot to the Beam Community in the next few weeks. Thanks for hanging in there

**Comment by epinault** [comment]
sounds good! if you need extra maintainers, let me know.

**Comment by yordis** [comment]
@brimatteng any updates?

**Comment by brimatteng** [comment]
Now under beam-community maintainership

**Comment by yordis** [comment]
@brimatteng let's gooo!

We need to make sure that https://hex.pm/orgs/ueberauth owns the Hex repo so we are able to release new versions

**Comment by aj-foster** [comment]
I see `ex_machina` listed under https://hex.pm/orgs/ueberauth, so I'll go ahead and close this. Thank you all for your contributions to the community! 🎉
