### ISSUE TITLE
Add optional 1ms delay for uuidv7 to aviod flakes.

### ISSUE THREAD

**Issue by dkuku** [beam-community/ex_machina#463]
We recently started using uuidv7 for ids in some services and I spotted that this causes problems in tests.
The id's are sorted but in practice in test when we generate multiple ones very quickly it causes issues:
```
--version-7---|        
------time----v---random part ------
0190b7b0-bf18-7792-8f43-8bdc55ed1f71
0190b7b0-bf18-76d6-8efb-49634cbd9489
0190b7b0-bf18-7310-a40d-98af1882c09d
0190b7b0-bf18-76f5-850e-ac25c022457b
0190b7b0-bf18-7b1f-985f-8f20069dc811
```
These are uuids generated in the same millisecond - as you can see the time part is sorted but the random part is not. 
This causes records generated later but in the same millisecond to possibly be sorted as older.
I propose to add optional 1ms delay to factories configured by a config setting. This will make the test suite slower by 0.1%  but will get rid of flaky tests. 
I'm open to other ideas how to solve it. Maybe a more precise version of uuidv7 for use just in factories would make sense ??

**Comment by btkostner** [comment]
I'd rather not introduce artificial delay into the library. Technically everything is working as intended™️ with UUIDv7 as this is one of the downsides / edge cases with it being time based. If you need something more precisely ordered, I'd recommend using another field to order by, like `DateTime` with micro precision.

With that said, if you want to add a 1ms delay between UUIDv7 generation, you should be able to add a `Process.sleep` in the generator function like so:

```elixir
def MyModule do
  use ExMachina

  def my_factory do
    Process.sleep(1)

    %MyStruct{
      id: uuid()
    }
  end
end
```

If that does not work, you can try doing this:

```elixir
def MyModule do
  use ExMachina

  def my_factory do
    %MyStruct{
      id: fn ->
        Process.sleep(1)
        uuid()
      end
    }
  end
end
```

Let me know if neither of those solutions work I can try to figure something else out.
